services:
  - type: web
    name: facedata-iist
    env: python
    region: oregon     # or "singapore" / "frankfurt" etc.
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

    autoDeploy: true

    envVars:
      DATA_FOLDER: /data
      UPLOAD_FOLDER: /uploads

    # Uncomment this if you want persistent storage for images:
    # disks:
    #   - name: data-disk
    #     mountPath: /data
    #     sizeGB: 1
