services:
  - type: web
    name: facedata-iist
    env: python
    plan: free
    region: oregon

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

    autoDeploy: true

    envVars:
      - key: DATA_FOLDER
        value: /data
      - key: UPLOAD_FOLDER
        value: /data/uploads

    disks:
      - name: data-disk
        mountPath: /data
        sizeGB: 1
